# Generated by Django 4.1.2 on 2022-10-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_location',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
