# Generated by Django 4.1.2 on 2022-10-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_vehicle_location_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_location',
            name='street_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
