# Generated by Django 4.1.2 on 2022-10-31 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_destination_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField(max_length=40)),
                ('departure', models.CharField(max_length=40)),
                ('destination', models.CharField(max_length=40)),
                ('start', models.DateTimeField(default='')),
                ('end', models.DateTimeField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_list',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('street_name', models.CharField(default='', max_length=20)),
                ('battery', models.CharField(default=100, max_length=5)),
                ('status', models.BooleanField(default=True)),
                ('repair', models.BooleanField(default=False)),
                ('v_type', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hirebike',
            name='bike_id',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.DeleteModel(
            name='HireBike',
        ),
        migrations.DeleteModel(
            name='vehicle_location',
        ),
        migrations.AddField(
            model_name='order',
            name='v_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.vehicle_list'),
        ),
    ]
