# Generated by Django 4.1.2 on 2022-10-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_order_vehicle_list_remove_hirebike_bike_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='duration',
            field=models.CharField(max_length=40),
        ),
    ]
