# Generated by Django 4.1.2 on 2022-11-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_vehicle_list_battery_alter_vehicle_list_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(default='', max_length=10),
        ),
    ]
