# Generated by Django 4.1.2 on 2022-11-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_destination_location_id_and_more'),
        ('customers', '0011_order_customer'),
    ]

    operations = [
    ]
