# Generated by Django 4.1.2 on 2022-11-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_merge_20221102_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_list',
            name='street_name',
            field=models.CharField(max_length=20),
        ),
    ]
