# Generated by Django 4.1.2 on 2022-11-03 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_alter_vehicle_list_street_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_list',
            name='street_name',
        ),
        migrations.AddField(
            model_name='vehicle_list',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_list', to='customers.destination_location'),
            preserve_default=False,
        ),
    ]
