# Generated by Django 4.1.2 on 2022-11-04 14:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0014_remove_vehicle_list_street_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(default="")),
                ("end", models.DateTimeField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="temp",
            fields=[
                ("order_id", models.IntegerField(primary_key=True, serialize=False)),
                ("duration", models.CharField(max_length=40)),
                ("departure", models.CharField(max_length=40)),
                ("destination", models.CharField(max_length=40)),
                ("customer", models.CharField(default="", max_length=10)),
                ("start", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "end",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "v_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.vehicle_list",
                    ),
                ),
            ],
        ),
    ]
